### ISSUE TITLE
Strange sequence behaviour

### ISSUE THREAD

**Issue by miguelpucela** [rgc99/irrigation_unlimited#29] opened 2021-07-20 12:32 UTC
Hello,

I'm having problems with sequences. I'm using version 2021.6.15.

I have the next configuration:

```
    - name: 'Riego Pinar'
      entity_id: 'switch.sonoff_1000aa7cb2'
      enabled: true
      zones:
       - name: 'Zona 1'
         enabled: true
         minimum: '00:00'
         maximum: '00:19'
         entity_id: 'switch.sonoff_10007802f0'
       - name: 'Zona 2'
         enabled: true
         minimum: '00:00'
         maximum: '00:19'
         entity_id: 'switch.sonoff_1000794f0b'
       - name: 'Zona 3'
         entity_id: 'switch.sonoff_1000049a5e'
         enabled: true
         minimum: '00:00'
         maximum: '00:19'
      sequences:
        - name: 'Secuencia Pinar'
          duration: '00:08'
          delay: '00:01'
          schedules:
            - name: 'Amanecer'
              time:
                sun: 'sunrise'
                after: '00:00'
              month: [mar, apr, may, jun, jul, aug, sep]
            - name: 'Después del anochecer'
              time:
                sun: 'sunset'
                after: '00:30'
              month: [mar, apr, may, jun, jul, aug, sep]
          zones:
            - zone_id: [2,3]
            - zone_id: 1
```

The result is that sometimes the sequence is not run completely and sometimes it is. The behaviour seems a bit random.

I don't know if you can reproduce it or somehow I can send you some log, so you can debug it.

Thank you and best regards.
Miguel

**Comment by miguelpucela** [comment] 2021-07-20 20:32
I have just observed that zones [2,3] have been activated after aprox. 5 minutes of scheduled starting time of a total of 11:30 minutes (8 minutes in config with a 143% multiplier).

I don't know if is somehow related, but in my configuration I forgot to write granularity and refresh_interval:

```
  granularity: 10
  refresh_interval: 30
```

**Comment by rgc99** [comment] 2021-07-21 01:58
It looks like you have an adjustment automation running. If so did it fire during the sequence run? Logs should help out here. I am thinking that the adjustment service call has interfered with the sequence run. It is not supposed to. I will run some tests on my side.

**Comment by miguelpucela** [comment] 2021-07-21 08:11
Yes, I have an adjustment automation. It's run every hour (o'clock), but it was not running at the time the irrigation was failing, as it was fired at 22:21.

I've changed log level to debug, so I can send you something interesting.

**Comment by rgc99** [comment] 2021-07-23 04:34
I have been able to reproduce and fix an issue where an adjustment during a running sequence will cause it not to complete. It will truncate the zones that have yet to run. This sounds very similar to the symptoms you are describing.

**Comment by miguelpucela** [comment] 2021-07-23 07:27
Great news!
I haven't been able to reproduce it during the last day and a half.

Thank you for your interest!

**Comment by rgc99** [comment] 2021-11-04 03:41
Is this issue fixed now?

**Comment by miguelpucela** [comment] 2021-11-04 03:45
I think so. During the last months it's irrigating well.
In any case, I won't continue irrigating until next spring.

**Closed** 2021-11-10 22:42 UTC
